#!/usr/bin/env bash
#The path to the file to be transferred
#The IP of the server we want to transfer the file to
#The username scp connects with
#The path to the SSH private key that scp uses


if [ '#$' -lt 4];
then
echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'

else

SERVER_IP='$2'
FILE_IP='$1'
SSH_KEY_PATH='$4'
USERNAME='$3'

scp -o StrictHostKeyChecking=no -i 'FILE_IP' 'SERVER_IP' 'USERNAME' 'SSH_KEY_PATH':~
fi
