#!/usr/bin/env bash

Configure Nginx server so that /redirect_me is redirecting to another page.

# installing nginx and update the parkage
sudo apt -y update
sudo apt -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

SERVER_CONFIGURATION=\
"server {
listen 80 default_server;
listen [::]:80 default_server;
root /var/www/html;
index index.html index.htm index.nginx-debian.html;
server_name _;

location / {
try_files \$uri \$uri/ =404;
}

location /redirect_me {
return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}

}"
EOF'
sudo service nginx reload
