#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page


sudo apt updtate -y
sudo apt install nginx -y
echo "Ceci n'est pas une page" > custom_404.html
sudo nano /var/www/html/custom_404.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}

	error_page 404 /404.html;
	location = /404.html{
	internal;
}
}" > default
sudo nano /etc/nginx/sites-available/default
sudo service nginx restart



