#!/usr/bin/env bash
# assigning a web server to run Nginx as the nginx user listening on port 8080.sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /var/log/nginx
pkill apache2
sudo -u nginx service nginx start
